name: Deploy Website to Netlify

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v4.0.0

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              run: pnpm run build:website

            - name: Install netlify-cli
              run: pnpm add -g netlify-cli

            - name: Check netlify-cli installation
              run: netlify --version

            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              run: |
                  netlify deploy --dir=website/dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
